### ISSUE TITLE
Changement sur la page de login GRDF?

### ISSUE THREAD

**Issue by fl0wfr** [mdeweerd/MetersToHA#26]
Bonjour,

J'obtiens l'erreur suivante de Chromium avec GRDF:

```
}
[1721901917.886][INFO]: Waiting for pending navigations...
[1721901917.887][INFO]: Done waiting for pending navigations. Status: ok
[1721901917.890][INFO]: Waiting for pending navigations...
[1721901917.891][INFO]: Done waiting for pending navigations. Status: ok
[1721901917.891][INFO]: [69a2800b9cfc7ab1f9214f2d3e612d43] RESPONSE FindElement ERROR no such element: Unable to locate element: {"method":"css selector","selector":"[id="pass"]"}
  (Session info: headless chrome=112.0.5615.165)
[1721901918.392][INFO]: [69a2800b9cfc7ab1f9214f2d3e612d43] COMMAND FindElement {
   "using": "css selector",
   "value": "[id=\"pass\"]"
}
```

Et dans service.log:

```
2024-07-25 12:05:09,209 : OK : Start the browser 
2024-07-25 12:05:09,209 : OK :  
2024-07-25 12:05:13,319 : OK : Connexion au site GRDF 
2024-07-25 12:06:13,536 : WW : Waiting for Password Traceback (most recent call last): -   File "/conf/apps/MetersToHA/meters_to_ha.py", line 3439, in doWork -     gazpar_file = crawler.get_gazpar_file() -   File "/conf/apps/MetersToHA/meters_to_ha.py", line 1756, in get_gazpar_file -     el_password = self.__wait.until( -   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 105, in until -     raise TimeoutException(message, screen, stacktrace) - selenium.common.exceptions.TimeoutException: Message: failed, page timeout (timeout=60) -
2024-07-25 12:06:13,536 : WW :  Encountered error -> Retrying once
2024-07-25 12:06:17,011 : OK : Connexion au site GRDF 
2024-07-25 12:07:17,205 : EE : Waiting for Password Message: failed, page timeout (timeout=60)
2024-07-25 12:07:17,261 : OK : Close Browser 
2024-07-25 12:07:17,264 : OK : Close Display 
2024-07-25 12:07:17,264 : EE :  Ended with error : // re-run with '--display' option if you can
```

Vu l'erreur je me demande si le code de la page de login n'a pas changé. Des avis?

**Comment by bsegault** [comment]
Bonjour,

J'ai la même erreur, je vais tenter d'analyser plus précisément et je mettrais à jour ce post 😄

**Comment by mdeweerd** [comment]
Bonjour
Désolé pour le délai - j'ai du mettre tout ce qui concernait HA sur très basse priorité.

J'ai intégré les divers propositions de changement de code hier.  Cela fonctionne pour moi désormais.
