### ISSUE TITLE
probème avec Chromium

### ISSUE THREAD

**Issue by hautfr** [mdeweerd/MetersToHA#28]
Traceback (most recent call last):
  File "MetersToHA/apps/meters_to_ha/meters_to_ha.py", line 3428, in doWork
    crawler.init()
  File "MetersToHA/apps/meters_to_ha/meters_to_ha.py", line 523, in init
    self.init_chromium()
  File "MetersToHA/apps/meters_to_ha/meters_to_ha.py", line 699, in init_chromium
    if log_level >= logging.WARNING:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'str' and 'int'

**Comment by mdeweerd** [comment]
Hi
Sorry for the delay - my TODO list has been growing, so I put of anything to do with HA.

The message is not related to Chromium as such, it indicates that either log_level or logging.WARNING is a string.

It seems that this can happen when the provided log_level is not valid.
I update the code which will log a message and fall back to the debug level in that case.
